id = "fe_language_zed"
name = "Fe Language"
version = "0.0.1"
schema_version = 1
authors = ["fe <you@example.com>"]
description = "Fe Language support."
repository = "https://github.com/ethereum/fe"

[language_servers.fe-lsp]
name = "Fe LSP server"
languages = ["Fe"]

[grammars.fe]
repository = "file:///home/micah/hacker-stuff-2023/fe-stuff/zed-fe/tree-sitter-fe"
commit = "0c0a937d806aa9e227b8c3d311756ecf98c5a7e6"
