id = "fe_language"
name = "Fe Language"
version = "0.0.2"
schema_version = 1
authors = ["Fe Language Team"]
description = "⚗️ Fe language support: diagnostics, completion, hover, inlay hints, go-to-definition, find references, rename, and more."
repository = "https://github.com/fe-lang/zed-fe"

[language_servers.fe-lsp]
name = "Fe LSP server"
languages = ["Fe"]

[grammars.fe]
repository = "https://github.com/argotorg/fe"
commit = "fe3257412b30c0d234b43c11edbeb5eee17142fd"
path = "crates/tree-sitter-fe"
